server:
  port: 8011

spring:
  application:
    name: xpoll-spring-cloud-service-consumer

eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: false # 向注册中心注册自己
    fetch-registry: true # 检索服务
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/