server:
  port: 8001
  
mybatis:
  config-location: classpath*:mybatis.cfg.xml
  type-aliases-package: cn.blmdz.cloud.provide.entity
  mapper-locations: classpath*:mapper/*Mapper.xml
  
spring:
  application:
    name: xpoll-spring-cloud-service-provide
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_test?autoReconnect=true&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: root
    
management:
  security:
    enabled: false